### ISSUE TITLE
access denied to downloadservice: token not used correctly?

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/arcservice#37]
We are getting this now. Probably the token is empty or not used or something like that. Could you please check?

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/arcservice/app.py", line 315, in get_arcinfo_json
    result.update(filelist_metrics(lines))
  File "/usr/local/lib/python3.10/dist-packages/arcservice/app.py", line 241, in filelist_metrics
    csv_header = str.strip(lines.__next__())
  File "/usr/local/lib/python3.10/dist-packages/arcservice/app.py", line 224, in stream_file_stats
    r.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: http://hub:5000/services/downloadservice/webdav/filelists/latest

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/arcservice/app.py", line 365, in metrics
    return get_arcinfo_json(), 200
  File "/usr/local/lib/python3.10/dist-packages/arcservice/app.py", line 318, in get_arcinfo_json
    result['file_list_status_code'] = http_er.request.status_code
AttributeError: 'PreparedRequest' object has no attribute 'status_code'
```

**Comment by volodymyrss** [comment]
@okolo , are you there?

**Comment by volodymyrss** [comment]
Do you think we could come back to this?

**Comment by volodymyrss** [comment]
I just close as stale.
